const String basePath = 'assets/';

const String fire = basePath + 'fire.jpg';
const String clapHands = basePath + 'claphand.png';
const String facebook = basePath + 'Facebook_logo.png';
const String google = basePath + 'google_logo.png';
const String icon = basePath + 'Icon.png';
const String splash = basePath + 'Splash.png';
const String thali = basePath + 'thali.png';
const String vegis = basePath + 'vegis.png';
const String store = basePath + 'store.png';
const String setting = basePath + 'settings.png';
const String map = basePath + 'location.png';
const String chichek1 = basePath + 'chikuu.png';
const String chichek = basePath + 'food123.png';
const String fruit = basePath + 'fruitsthali.jpg';
const String fruitfood = basePath + 'topFood.jpg';
const String momos = basePath + 'download.jpg';
const String salat = basePath + 'salat.png';
